module.exports = {
  apps: [
    {
      name: 'electricalwizard',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: '512M',
      env_file: '.env',
      watch: false,
    },
    {
      name: 'electricalwizard-web',
      script: 'dist/web/index.js',
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: '256M',
      env_file: '.env',
      env: {
        NODE_ENV: 'production',
      },
      watch: false,
    },
    {
      name: 'electricalwizard-dashboard',
      script: 'node_modules/next/dist/bin/next',
      args: 'start --port 8450',
      cwd: './dashboard',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
      },
      watch: false,
    },
  ],
};
